# Generated by Django 3.2.7 on 2021-09-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_product_id_product_detail_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=8000)),
                ('polarity', models.CharField(max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainApp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_detail',
        ),
    ]
