# Generated by Django 3.2.7 on 2021-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210927_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='polarity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
