# Generated by Django 3.2.8 on 2021-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210928_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=8000)),
                ('polarity', models.CharField(max_length=10, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
